name: bctk

x-bctk-common-env: &bctk-common-env
  CLICKHOUSE_DB: "${CLICKHOUSE_DB}"
  CLICKHOUSE_USER: "${CLICKHOUSE_APP_USER}"
  CLICKHOUSE_PASSWORD: "${CLICKHOUSE_APP_PASSWORD}"
  CLICKHOUSE_URL: "http://${CLICKHOUSE_IP}:${CLICKHOUSE_PORT}"

x-bctk-clickhouse-env: &bctk-clickhouse-env
  environment:
    <<: *bctk-common-env

x-bctk-app-env: &bctk-app-env
  environment:
    <<: *bctk-common-env
    AVALANCHE_RPC_URL: "${AVALANCHE_RPC_URL}"
    NODE_ENV: production
    # NODE_ENV: development   # WIP

volumes:
  bctk-vclickhouse:
    name: bctk_vclickhouse
  
networks:
  bctk-network:
    name: bctk_network
    driver: bridge
    ipam:
      config:
        # specific range to avoid conflicts with the bridge network (172.17)
        - subnet: ${DOCKER_SUBNET_BASE}.0/16

services:

  clickhouse:
    container_name: bctk_clickhouse
    image: clickhouse/clickhouse-server:24.10.1
    restart: always
    <<: *bctk-clickhouse-env
    volumes:
      - bctk-vclickhouse:/var/lib/clickhouse
      - ./db/startup_scripts.xml:/etc/clickhouse-server/config.d/startup_scripts.xml:ro
      # - ./db/users.xml:/etc/clickhouse-server/users.d/users.xml:ro    # TODO
    networks:
      bctk-network:
        ipv4_address: ${DOCKER_SUBNET_BASE}.101
  
  application:
    container_name: bctk_app
    build: 
      context: .
      dockerfile: src/Dockerfile
    restart: always
    depends_on:
      - clickhouse
    <<: *bctk-app-env
    volumes:
      - ${DATA_DIR}:/srv/data
      - ./config:/config
      - ./dist:/dist
      - ./src:/src    # useful to enable respawn in dev mode (WIP)
    ports:
      - "3000:3000"
    networks:
      bctk-network:
        ipv4_address: ${DOCKER_SUBNET_BASE}.201
